2024-08-06 12:24:00,742 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 12:28:00,228 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 12:32:00,360 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 12:36:00,366 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 12:40:00,488 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 12:44:01,073 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 12:48:00,118 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 12:52:00,797 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 12:56:00,859 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:00:00,875 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:04:00,895 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:08:01,069 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:12:00,220 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:16:00,240 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:20:00,368 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:24:00,673 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:28:00,688 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:32:00,881 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:36:00,039 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:40:00,397 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:44:00,402 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:48:00,536 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:52:00,690 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 13:56:00,960 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 14:00:01,128 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 14:04:00,286 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 14:08:00,530 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
2024-08-06 14:12:00,723 ERROR scheduler Exception in Enqueue Events for Site library
Traceback (most recent call last):
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
      ^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
                                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/dorah/Downloads/bitty/library_management_system/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_ac7c12bdd8365ca2'")
